import { TaxonomyConfig } from './types';

export const wasteTaxonomy: TaxonomyConfig = {
  taxonomyName: 'Municipal Waste & Circular Economy Taxonomy',
  domain: 'municipal_waste',
  title: 'Smart Waste Categorizer & Circular Impact',
  subtitle: 'AI-assisted segregation engine with real-time carbon offset telemetry',
  searchPlaceholder: 'Search item (e.g. plastic bottle, banana peel, lithium battery, cardboard)...',
  sampleQueries: [
    'Plastic milk jug',
    'Banana peel',
    'Cardboard packaging',
    'Soda can',
    'Old smartphone battery',
    'Medical blister pack',
  ],
  categories: [
    {
      id: 'plastic',
      name: 'Non-biodegradable (Plastic & Polymers)',
      badgeLabel: 'Blue Recyclable Bin',
      badgeColor: 'blue',
      keywords: ['plastic', 'bottle', 'pet', 'wrapper', 'polythene', 'polybag', 'container', 'straw', 'cup', 'jug', 'pouch'],
      handlingInstructions: 'Rinse thoroughly and flatten containers before binning. Avoid burning to prevent toxic fumes.',
      impactMetricLabel: 'CO₂ Avoided',
      impactMultiplier: 1.5,
      dos: ['Rinse beverage bottles & dairy pouches', 'Flatten jugs and packaging to save volume', 'Gather small bottle caps inside larger containers'],
      donts: ['Never incinerate plastic', 'Do not contaminate with heavy grease or food', 'Avoid mixed thermocol single-use cups'],
      lifecycleFact: 'Recycling 1 ton of plastic saves ~5,774 kWh of electricity and 16 barrels of oil.',
    },
    {
      id: 'organic',
      name: 'Biodegradable (Organic & Kitchen Wet Waste)',
      badgeLabel: 'Green Wet Bin',
      badgeColor: 'green',
      keywords: ['banana', 'food', 'peel', 'apple', 'vegetable', 'fruit', 'leaf', 'tea bag', 'egg shell', 'coffee', 'organic', 'leftover', 'scraps'],
      handlingInstructions: 'Compost at source or place in breathable green bins. Excellent feedstock for biogas and organic fertilizers.',
      impactMetricLabel: 'Methane Mitigated',
      impactMultiplier: 0.8,
      dos: ['Use breathable compost liners or aerated buckets', 'Balance nitrogen greens (fruit peels) with carbon browns (dry leaves)', 'Collect vegetable trimmings separately for biogas feed'],
      donts: ['Never mix plastic liners or cling wraps in wet bins', 'Do not include chemical treated woods or synthetic cleansers', 'Avoid letting stagnant liquid pool over 48 hours'],
      lifecycleFact: 'Composted kitchen waste cuts landfill methane emissions by more than 90%.',
    },
    {
      id: 'paper',
      name: 'Recyclable (Paper & Cardboard)',
      badgeLabel: 'Blue Dry Bin',
      badgeColor: 'blue',
      keywords: ['paper', 'box', 'cardboard', 'newspaper', 'carton', 'magazine', 'envelope', 'book', 'notebook', 'mailer'],
      handlingInstructions: 'Keep dry and fold corrugated cardboard flat. Keep separate from liquids.',
      impactMetricLabel: 'Trees Saved Equivalent',
      impactMultiplier: 1.1,
      dos: ['Flatten shipping cartons completely', 'Bundle clean newspapers with natural twine', 'Store shreddings inside a paper envelope'],
      donts: ['Do not mix greasy pizza boxes or oil-soaked paper', 'Avoid plastic laminated receipts', 'Never mix wet napkins with dry paper bundles'],
      lifecycleFact: 'Every ton of recycled paper preserves 17 mature trees and 7,000 gallons of water.',
    },
    {
      id: 'metal',
      name: 'Recyclable (Metals & Alloys)',
      badgeLabel: 'Yellow Metal Bin',
      badgeColor: 'yellow',
      keywords: ['metal', 'can', 'tin', 'aluminum', 'foil', 'iron', 'steel', 'copper', 'soda can', 'aerosol'],
      handlingInstructions: 'Rinse food cans clean and press lid flaps inward to protect sanitation personnel.',
      impactMetricLabel: 'Energy Saved vs Virgin Ore',
      impactMultiplier: 3.2,
      dos: ['Rinse sauce residues completely', 'Crimp sharp tin edges inward safely', 'Compress clean aluminum foil into a ball'],
      donts: ['Do not throw pressurized paint aerosols without venting', 'Avoid mixing heavy construction steel into household cans'],
      lifecycleFact: 'Recycling aluminum saves 95% of the energy required to smelt virgin bauxite.',
    },
    {
      id: 'ewaste',
      name: 'E-Waste & High Value Electronics',
      badgeLabel: 'Red E-Drop Station',
      badgeColor: 'red',
      keywords: ['battery', 'phone', 'laptop', 'charger', 'cable', 'circuit', 'bulb', 'led', 'electronic', 'e-waste', 'wire', 'tablet'],
      handlingInstructions: 'Contains hazardous heavy metals (lead, cadmium). Hand over to certified e-waste recyclers only.',
      impactMetricLabel: 'Heavy Metals Contained',
      impactMultiplier: 4.5,
      dos: ['Tape battery terminals with electrical tape', 'Back up and factory reset digital memory storage', 'Drop off at authorized municipal e-waste kiosks'],
      donts: ['Never discard batteries into regular trash', 'Do not crush, incinerate or puncture swollen lithium cells'],
      lifecycleFact: '1 million recycled mobile phones recover 35,000 lbs of copper and 770 lbs of silver.',
    },
  ],
};

export const warehouseInventoryTaxonomy: TaxonomyConfig = {
  taxonomyName: 'Warehouse Material & SKU Sorter',
  domain: 'warehouse_logistics',
  title: 'Intelligent Inbound SKU Sorter',
  subtitle: 'Automated warehouse routing, storage hazard classification, and rack zoning',
  searchPlaceholder: 'Search SKU or material (e.g. pallet, lithium ion, motor oil, fragile glassware)...',
  sampleQueries: ['Lithium battery pack', 'Fragile crystal glass', 'Motor engine oil', 'Corrugated pallet'],
  categories: [
    {
      id: 'hazardous_flammable',
      name: 'Hazard Class 3 (Flammable Liquids & Aerosols)',
      badgeLabel: 'Zone H - Fireproof Bunker',
      badgeColor: 'red',
      keywords: ['oil', 'solvent', 'alcohol', 'flammable', 'paint', 'aerosol', 'fuel', 'petroleum'],
      handlingInstructions: 'Store strictly in temperature-controlled explosion-proof cabinets with grounding rods.',
      dos: ['Verify tamper-evident seal intact', 'Inspect for vapor leakage'],
      donts: ['Do not store near open electrical switches or heaters'],
    },
    {
      id: 'fragile_highvalue',
      name: 'High Care / Fragile Goods',
      badgeLabel: 'Zone F - Padded Low-Racks',
      badgeColor: 'purple',
      keywords: ['glass', 'crystal', 'lens', 'camera', 'monitor', 'porcelain', 'fragile', 'screen'],
      handlingInstructions: 'Handle with pneumatic lift cups and double air-cushion packaging.',
      dos: ['Apply Fragile / This Side Up indicator', 'Store on bottom two tiers'],
      donts: ['Never stack more than 2 boxes high'],
    },
    {
      id: 'bulk_dry',
      name: 'Standard Bulk Dry Cargo',
      badgeLabel: 'Zone A - High-Bay Racking',
      badgeColor: 'blue',
      keywords: ['pallet', 'carton', 'box', 'textile', 'paper', 'plastic', 'dry'],
      handlingInstructions: 'Standard automated forklift high-bay routing.',
      dos: ['Wrap pallet in 80-gauge stretch film', 'Weight balance load across beams'],
      donts: ['Do not exceed 1,200 kg per bay level'],
    },
  ],
};
